## <b> The Play Store apps data has enormous potential to drive app-making businesses to success. Actionable insights can be drawn for developers to work on and capture the Android market. </b>

## <b> Each app (row) has values for catergory, rating, size, and more. Another dataset contains customer reviews of the android apps.</b>

## <b> Explore and analyze the data to discover key factors responsible for app engagement and success. </b>

In [18]:
import pandas as pd
import numpy as np 
import matplotlib as plt
%matplotlib inline

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
file_path = '/content/drive/MyDrive/Untitled folder/Play Store Data (3).csv'
playapp_df=pd.read_csv(file_path)

In [21]:
playapp_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [22]:
playapp_df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [23]:
playapp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [24]:
playapp_df.shape

(10841, 13)

# Question 1= Find the best Rating Application and its Review size and Downloads

In [25]:
playapp_df.Rating.unique()

array([ 4.1,  3.9,  4.7,  4.5,  4.3,  4.4,  3.8,  4.2,  4.6,  3.2,  4. ,
        nan,  4.8,  4.9,  3.6,  3.7,  3.3,  3.4,  3.5,  3.1,  5. ,  2.6,
        3. ,  1.9,  2.5,  2.8,  2.7,  1. ,  2.9,  2.3,  2.2,  1.7,  2. ,
        1.8,  2.4,  1.6,  2.1,  1.4,  1.5,  1.2, 19. ])

In [26]:
playapp_df.drop([10472],axis=0,inplace=True)
playapp_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [27]:
playapp_df.Rating.unique()

array([4.1, 3.9, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4. , nan, 4.8,
       4.9, 3.6, 3.7, 3.3, 3.4, 3.5, 3.1, 5. , 2.6, 3. , 1.9, 2.5, 2.8,
       2.7, 1. , 2.9, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5,
       1.2])

In [28]:
best_rating = playapp_df[playapp_df['Rating'] == 5.]
best_rating[['App','Reviews','Installs','Rating']]

                                              App Reviews Installs  Rating
329                  Hojiboy Tojiboyev Life Hacks      15   1,000+     5.0
612                 American Girls Mobile Numbers       5   1,000+     5.0
615                                  Awake Dating       2     100+     5.0
633                         Spine- The dating app       5     500+     5.0
636    Girls Live Talk - Free Text and Video Chat       6     100+     5.0
...                                           ...     ...      ...     ...
10721                           Mad Dash Fo' Cash      14     100+     5.0
10742                       GKPB FP Online Church      32   1,000+     5.0
10776                            Monster Ride Pro       1      10+     5.0
10820                             Fr. Daoud Lamei      22   1,000+     5.0
10837            Fr. Mike Schmitz Audio Teachings       4     100+     5.0

[274 rows x 4 columns]

# Question 2=Application having more than 5000000+ installs

In [29]:
playapp_df.Installs.unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0'], dtype=object)

# remove + signs

In [30]:
playapp_df['Installs'] = playapp_df['Installs'].replace({'\+':'',',':'','Free':0,'':0}, regex=True)

In [31]:
playapp_df['Installs']

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs, Length: 10840, dtype: object

In [32]:
playstore_app = playapp_df[playapp_df['Installs'].astype(int) > 5000000 ]
playstore_app[['App']]

                                                     App
3                                  Sketch - Draw & Paint
12                        Tattoo Name On My Photo Editor
19                                          ibis Paint X
42                            Textgram - write on photos
45     Canva: Poster, banner, card maker & graphic de...
...                                                  ...
10729                            MX Player Codec (ARMv7)
10740                                         PhotoFunia
10781                               Modern Strike Online
10784                                         Big Hunter
10840      iHoroscope - 2018 Daily Horoscope & Astrology

[2080 rows x 1 columns]

# Question 3= All the 17+ content rating Application

In [33]:
playapp_df = playapp_df[playapp_df['Content Rating'] == 'Mature 17+']
playapp_df[['App']]

                                                App
129             Secrets of beauty, youth and health
133                  Dresses Ideas & Fashions +3000
134                   Lady adviser (beauty, health)
166                               Read books online
170                                         Flybook
...                                             ...
10735                                   FP VoiceBot
10765               Chat For Strangers - Video Chat
10783  Modern Counter Terror Attack – Shooting Game
10826     Frim: get new friends on local chat rooms
10839                 The SCP Foundation DB fr nn5n

[499 rows x 1 columns]

# Question 4 Kindly tell the best category in terms of best Reviews

In [34]:
playapp_df.Category.unique()

array(['BEAUTY', 'BOOKS_AND_REFERENCE', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'HEALTH_AND_FITNESS',
       'LIFESTYLE', 'GAME', 'MEDICAL', 'SOCIAL', 'PHOTOGRAPHY', 'SPORTS',
       'TRAVEL_AND_LOCAL', 'PERSONALIZATION', 'PARENTING',
       'NEWS_AND_MAGAZINES', 'FAMILY', 'TOOLS', 'VIDEO_PLAYERS',
       'MAPS_AND_NAVIGATION', 'BUSINESS', 'WEATHER', 'SHOPPING',
       'PRODUCTIVITY'], dtype=object)

In [35]:
max_category = playapp_df.sort_values('Category', ascending=False)
max_category[['Category','Reviews']]

                 Category Reviews
7491              WEATHER   20001
4632        VIDEO_PLAYERS   93638
8767        VIDEO_PLAYERS    6716
6334        VIDEO_PLAYERS     414
3122     TRAVEL_AND_LOCAL  751551
...                   ...     ...
170   BOOKS_AND_REFERENCE    1778
166   BOOKS_AND_REFERENCE   91615
133                BEAUTY     473
134                BEAUTY      30
129                BEAUTY      77

[499 rows x 2 columns]